// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/mining.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to mine a new block
type MineBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	MinerAddress  string                 `protobuf:"bytes,2,opt,name=miner_address,json=minerAddress,proto3" json:"miner_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MineBlockRequest) Reset() {
	*x = MineBlockRequest{}
	mi := &file_proto_mining_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MineBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MineBlockRequest) ProtoMessage() {}

func (x *MineBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mining_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MineBlockRequest.ProtoReflect.Descriptor instead.
func (*MineBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_mining_proto_rawDescGZIP(), []int{0}
}

func (x *MineBlockRequest) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *MineBlockRequest) GetMinerAddress() string {
	if x != nil {
		return x.MinerAddress
	}
	return ""
}

// Transaction data
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	TransactionId []byte                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_mining_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mining_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_mining_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetTransactionId() []byte {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

// Response after mining a block
type MineBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BlockHash     string                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MineBlockResponse) Reset() {
	*x = MineBlockResponse{}
	mi := &file_proto_mining_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MineBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MineBlockResponse) ProtoMessage() {}

func (x *MineBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mining_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MineBlockResponse.ProtoReflect.Descriptor instead.
func (*MineBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_mining_proto_rawDescGZIP(), []int{2}
}

func (x *MineBlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MineBlockResponse) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *MineBlockResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request to get blockchain status
type BlockchainStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockchainStatusRequest) Reset() {
	*x = BlockchainStatusRequest{}
	mi := &file_proto_mining_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainStatusRequest) ProtoMessage() {}

func (x *BlockchainStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mining_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainStatusRequest.ProtoReflect.Descriptor instead.
func (*BlockchainStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_mining_proto_rawDescGZIP(), []int{3}
}

// Response containing blockchain status
type BlockchainStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Height          int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	LatestBlockHash string                 `protobuf:"bytes,2,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash,omitempty"`
	Difficulty      int32                  `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockchainStatusResponse) Reset() {
	*x = BlockchainStatusResponse{}
	mi := &file_proto_mining_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainStatusResponse) ProtoMessage() {}

func (x *BlockchainStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mining_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainStatusResponse.ProtoReflect.Descriptor instead.
func (*BlockchainStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_mining_proto_rawDescGZIP(), []int{4}
}

func (x *BlockchainStatusResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockchainStatusResponse) GetLatestBlockHash() string {
	if x != nil {
		return x.LatestBlockHash
	}
	return ""
}

func (x *BlockchainStatusResponse) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

// Request to get pending transactions
type PendingTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingTransactionsRequest) Reset() {
	*x = PendingTransactionsRequest{}
	mi := &file_proto_mining_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingTransactionsRequest) ProtoMessage() {}

func (x *PendingTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mining_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingTransactionsRequest.ProtoReflect.Descriptor instead.
func (*PendingTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mining_proto_rawDescGZIP(), []int{5}
}

// Response containing pending transactions
type PendingTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingTransactionsResponse) Reset() {
	*x = PendingTransactionsResponse{}
	mi := &file_proto_mining_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingTransactionsResponse) ProtoMessage() {}

func (x *PendingTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mining_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingTransactionsResponse.ProtoReflect.Descriptor instead.
func (*PendingTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_mining_proto_rawDescGZIP(), []int{6}
}

func (x *PendingTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_proto_mining_proto protoreflect.FileDescriptor

const file_proto_mining_proto_rawDesc = "" +
	"\n" +
	"\x12proto/mining.proto\x12\x06mining\"p\n" +
	"\x10MineBlockRequest\x127\n" +
	"\ftransactions\x18\x01 \x03(\v2\x13.mining.TransactionR\ftransactions\x12#\n" +
	"\rminer_address\x18\x02 \x01(\tR\fminerAddress\"\x8e\x01\n" +
	"\vTransaction\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\fR\rtransactionId\"q\n" +
	"\x11MineBlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\tR\tblockHash\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x19\n" +
	"\x17BlockchainStatusRequest\"~\n" +
	"\x18BlockchainStatusResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12*\n" +
	"\x11latest_block_hash\x18\x02 \x01(\tR\x0flatestBlockHash\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\x05R\n" +
	"difficulty\"\x1c\n" +
	"\x1aPendingTransactionsRequest\"V\n" +
	"\x1bPendingTransactionsResponse\x127\n" +
	"\ftransactions\x18\x01 \x03(\v2\x13.mining.TransactionR\ftransactions2\x94\x02\n" +
	"\rMiningService\x12B\n" +
	"\tMineBlock\x12\x18.mining.MineBlockRequest\x1a\x19.mining.MineBlockResponse\"\x00\x12Z\n" +
	"\x13GetBlockchainStatus\x12\x1f.mining.BlockchainStatusRequest\x1a .mining.BlockchainStatusResponse\"\x00\x12c\n" +
	"\x16GetPendingTransactions\x12\".mining.PendingTransactionsRequest\x1a#.mining.PendingTransactionsResponse\"\x00B\x11Z\x0fdyp_chain/protob\x06proto3"

var (
	file_proto_mining_proto_rawDescOnce sync.Once
	file_proto_mining_proto_rawDescData []byte
)

func file_proto_mining_proto_rawDescGZIP() []byte {
	file_proto_mining_proto_rawDescOnce.Do(func() {
		file_proto_mining_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mining_proto_rawDesc), len(file_proto_mining_proto_rawDesc)))
	})
	return file_proto_mining_proto_rawDescData
}

var file_proto_mining_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_mining_proto_goTypes = []any{
	(*MineBlockRequest)(nil),            // 0: mining.MineBlockRequest
	(*Transaction)(nil),                 // 1: mining.Transaction
	(*MineBlockResponse)(nil),           // 2: mining.MineBlockResponse
	(*BlockchainStatusRequest)(nil),     // 3: mining.BlockchainStatusRequest
	(*BlockchainStatusResponse)(nil),    // 4: mining.BlockchainStatusResponse
	(*PendingTransactionsRequest)(nil),  // 5: mining.PendingTransactionsRequest
	(*PendingTransactionsResponse)(nil), // 6: mining.PendingTransactionsResponse
}
var file_proto_mining_proto_depIdxs = []int32{
	1, // 0: mining.MineBlockRequest.transactions:type_name -> mining.Transaction
	1, // 1: mining.PendingTransactionsResponse.transactions:type_name -> mining.Transaction
	0, // 2: mining.MiningService.MineBlock:input_type -> mining.MineBlockRequest
	3, // 3: mining.MiningService.GetBlockchainStatus:input_type -> mining.BlockchainStatusRequest
	5, // 4: mining.MiningService.GetPendingTransactions:input_type -> mining.PendingTransactionsRequest
	2, // 5: mining.MiningService.MineBlock:output_type -> mining.MineBlockResponse
	4, // 6: mining.MiningService.GetBlockchainStatus:output_type -> mining.BlockchainStatusResponse
	6, // 7: mining.MiningService.GetPendingTransactions:output_type -> mining.PendingTransactionsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mining_proto_init() }
func file_proto_mining_proto_init() {
	if File_proto_mining_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mining_proto_rawDesc), len(file_proto_mining_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mining_proto_goTypes,
		DependencyIndexes: file_proto_mining_proto_depIdxs,
		MessageInfos:      file_proto_mining_proto_msgTypes,
	}.Build()
	File_proto_mining_proto = out.File
	file_proto_mining_proto_goTypes = nil
	file_proto_mining_proto_depIdxs = nil
}
